<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Spatie\Tags\Tag;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tags = [
            'Laravel',
            'PHP',
            'JavaScript',
            'Vue.js',
            'React',
            'Node.js',
            'HTML',
            'CSS',
            'MySQL',
            'PostgreSQL',
            'MongoDB',
            'API Development',
            'Web Development',
            'Software Engineering',
            'DevOps',
            'Machine Learning',
            'Artificial Intelligence',
            'Blockchain',
            'Cloud Computing',
            'Cybersecurity',
            'Mobile Development',
            'Game Development',
            'Data Science',
            'UI/UX Design',
            'Agile Methodology',
            'Scrum',
            'Testing',
            'Continuous Integration',
            'Continuous Deployment',
            'REST',
            'GraphQL',
            'Docker',
            'Kubernetes',
            'AWS',
            'Azure',
            'Google Cloud',
            'Firebase',
            'SASS',
            'LESS',
            'Bootstrap',
            'Tailwind CSS',
            'Material UI',
            'jQuery',
            'TypeScript',
            'ES6',
            'Webpack',
            'Vite',
            'Gulp',
            'Grunt',
            'Composer',
            'NPM',
            'Yarn',
            'Babel',
            'Redis',
            'Memcached',
            'ElasticSearch',
            'RabbitMQ',
            'Kafka',
            'Microservices',
            'Serverless',
            'PWA',
            'SPA',
            'MVC',
            'TDD',
            'BDD',
            'Unit Testing',
            'Integration Testing',
            'E2E Testing',
            'Jest',
            'Mocha',
            'Chai',
            'PHPUnit',
            'Cypress',
            'Selenium',
            'Playwright',
            'Jenkins',
            'GitHub Actions',
            'GitLab CI',
            'Bitbucket Pipelines',
            'OAuth',
            'JWT',
            'SSO',
            'OpenID Connect',
            'SAML',
            'Encryption',
            'SSL',
            'TLS',
            'OAuth2',
            'WebSockets',
            'Socket.IO',
            'MQTT',
            'gRPC',
            'RESTful API',
            'API Gateway',
            'Load Balancing',
            'Reverse Proxy',
            'Nginx',
            'Apache',
            'Caddy',
            'DigitalOcean',
            'Heroku',
            'Netlify',
            'Vercel',
            'CI/CD',
            'Monitoring',
            'Logging',
            'Prometheus',
            'Grafana',
            'Sentry',
            'New Relic',
            'Datadog',
            'A/B Testing',
            'Feature Flags',
            'Localization',
            'Internationalization',
            'Accessibility',
            'SEO',
            'Performance Optimization',
            'Caching',
            'Responsive Design',
            'Mobile First',
            'Cross-browser Compatibility',
            'Progressive Enhancement',
            'Headless CMS',
            'Contentful',
            'Strapi',
            'Sanity',
            'WordPress',
            'Drupal',
            'Joomla',
            'Shopify',
            'Magento',
            'WooCommerce',
            'BigCommerce',
            'E-commerce',
            'Payment Integration',
            'Stripe',
            'PayPal',
            'Square',
            'Analytics',
            'Google Analytics',
            'Mixpanel',
            'Hotjar',
            'User Experience',
            'User Research',
            'Wireframing',
            'Prototyping',
            'Figma',
            'Sketch',
            'Adobe XD',
            'Photoshop',
            'Illustrator',
            'Version Control',
            'Git',
            'SVN',
            'Mercurial',
            'Code Review',
            'Pair Programming',
            'Mentoring',
            'Technical Writing',
            'Documentation',
            'Open Source',
            'Community',
            'Hackathons',
            'Startups',
            'Entrepreneurship',
            'Freelancing',
            'Remote Work',
            'Team Collaboration',
            'Project Management',
            'Kanban',
            'Jira',
            'Trello',
            'Asana',
            'Notion',
            'Slack',
            'Zoom',
            'Agile',
            'Scrum Master',
            'Product Owner',
            'Stakeholder Management',
            'Requirements Gathering',
            'MVP',
            'Release Management',
            'Change Management',
            'Incident Management',
            'Root Cause Analysis',
            'Retrospective',
            'Continuous Improvement',
            'Quality Assurance',
            'Risk Management',
            'Time Management',
            'Leadership',
            'Communication',
            'Problem Solving',
            'Critical Thinking',
            'Creativity',
            'Adaptability',
            'Emotional Intelligence',
            'Collaboration',
            'Conflict Resolution',
            'Decision Making',
            'Goal Setting',
            'Self-motivation',
            'Learning',
            'Growth Mindset',
            'Feedback',
            'Networking',
            'Personal Branding',
            'Portfolio',
            'Resume',
            'Interviewing',
            'Job Search',
            'Career Development',
            'Work-life Balance',
            'Wellness',
            'Diversity',
            'Inclusion',
            'Ethics',
            'Sustainability',
            'Philanthropy',
            'Volunteering',
            'Community Service',
            'Public Speaking',
            'Teaching',
            'Coaching',
            'Consulting',
            'Advisory',
            'Board Membership',
            'Investment',
            'Venture Capital',
            'Angel Investing',
            'Crowdfunding',
            'Financial Planning',
            'Budgeting',
            'Accounting',
            'Taxation',
            'Legal',
            'Compliance',
            'Intellectual Property',
            'Patents',
            'Trademarks',
            'Copyright',
            'Contracts',
            'Negotiation',
            'Procurement',
            'Supply Chain',
            'Logistics',
            'Operations',
            'Manufacturing',
            'Quality Control',
            'Inventory Management',
            'Customer Service',
            'Sales',
            'Marketing',
            'Branding',
            'Advertising',
            'Social Media',
            'Content Marketing',
            'Email Marketing',
            'Affiliate Marketing',
            'Market Research',
            'Business Development',
            'Strategy',
            'Planning',
            'Execution',
            'Analysis',
            'Reporting',
            'KPIs',
            'OKRs',
            'ROI',
            'Benchmarking',
            'Forecasting',
            'Trend Analysis',
            'Data Visualization',
            'Big Data',
            'Data Engineering',
            'Data Analytics',
            'Business Intelligence',
            'ETL',
            'Data Warehousing',
            'Data Mining',
            'Predictive Analytics',
            'Artificial Neural Networks',
            'Deep Learning',
            'Natural Language Processing',
            'Computer Vision',
            'Robotics',
            'Automation',
            'IoT',
            'Edge Computing',
            'Quantum Computing',
            'Augmented Reality',
            'Virtual Reality',
            'Mixed Reality',
            '3D Modeling',
            'Animation',
            'Video Production',
            'Audio Engineering',
            'Music Production',
            'Game Design',
            'Game Programming',
            'Level Design',
            'Esports',
            'Streaming',
            'Podcasting',
            'Blogging',
            'Vlogging',
            'Photography',
            'Photo Editing',
            'Film Making',
            'Screenwriting',
            'Storytelling',
            'Creative Writing',
            'Copywriting',
            'Editing',
            'Proofreading',
            'Translation',
            'Transcription',
            'Subtitling',
            'Localization',
            'Voice Acting',
            'Acting',
            'Directing',
            'Producing',
            'Event Planning',
            'Event Management',
            'Public Relations',
            'Media Relations',
            'Crisis Management',
            'Fundraising',
            'Grant Writing',
            'Sponsorship',
            'Donor Relations',
            'Alumni Relations',
            'Membership',
            'Volunteer Management',
            'Board Development',
            'Strategic Partnerships',
            'Advocacy',
            'Policy',
            'Government Relations',
            'Lobbying',
            'Research',
            'Evaluation',
            'Impact Assessment',
            'Sustainability Reporting',
            'Carbon Footprint',
            'Renewable Energy',
            'Green Technology',
            'Circular Economy',
            'Social Impact',
            'Corporate Social Responsibility',
            'Philanthropy',
            'Nonprofit Management',
            'Grant Management',
            'Program Management',
            'Service Design',
            'Human-centered Design',
            'Design Thinking',
            'Systems Thinking',
            'Behavioral Science',
            'Psychology',
            'Sociology',
            'Anthropology',
            'Economics',
            'Political Science',
            'History',
            'Philosophy',
            'Linguistics',
            'Literature',
            'Art',
            'Music',
            'Theater',
            'Dance',
            'Film',
            'Architecture',
            'Urban Planning',
            'Geography',
            'Environmental Science',
            'Biology',
            'Chemistry',
            'Physics',
            'Mathematics',
            'Statistics',
            'Astronomy',
            'Geology',
            'Meteorology',
            'Oceanography',
            'Ecology',
            'Genetics',
            'Microbiology',
            'Neuroscience',
            'Medicine',
            'Nursing',
            'Pharmacy',
            'Dentistry',
            'Veterinary Medicine',
            'Public Health',
            'Nutrition',
            'Kinesiology',
            'Sports Science',
            'Education',
            'Teaching',
            'Curriculum Development',
            'Instructional Design',
            'E-learning',
            'EdTech',
            'Special Education',
            'Early Childhood Education',
            'Higher Education',
            'Adult Education',
            'Workforce Development',
            'Training',
            'Professional Development',
            'Leadership Development',
            'Organizational Development',
            'Change Leadership',
            'Talent Management',
            'Recruitment',
            'Onboarding',
            'Employee Engagement',
            'Performance Management',
            'Compensation',
            'Benefits',
            'HR Analytics',
            'Labor Relations',
            'Diversity and Inclusion',
            'Workplace Wellness',
            'Occupational Health',
            'Safety',
            'Risk Assessment',
            'Crisis Response',
            'Emergency Management',
            'Disaster Recovery',
            'Business Continuity',
            'Supply Chain Resilience',
            'Cyber Resilience',
            'Incident Response',
            'Threat Intelligence',
            'Vulnerability Management',
            'Penetration Testing',
            'Security Operations',
            'Security Awareness',
            'Privacy',
            'Data Protection',
            'GDPR',
            'CCPA',
            'HIPAA',
            'PCI DSS',
            'SOX',
            'FISMA',
            'ISO 27001',
            'NIST',
            'COBIT',
            'ITIL',
            'CMMI',
            'Six Sigma',
            'Lean',
            'Kaizen',
            'Total Quality Management',
            'Process Improvement',
            'Business Process Management',
            'Workflow Automation',
            'Robotic Process Automation',
            'Digital Transformation',
            'Innovation',
            'Disruption',
            'Blue Ocean Strategy',
            'Design Sprint',
            'Growth Hacking',
            'Customer Success',
            'Customer Experience',
            'User Onboarding',
            'Churn Reduction',
            'Net Promoter Score',
            'Customer Feedback',
            'Support',
            'Help Desk',
            'Ticketing',
            'Knowledge Base',
            'Self-service',
            'Chatbots',
            'Live Chat',
            'Call Center',
            'CRM',
            'Salesforce',
            'HubSpot',
            'Zoho',
            'Pipedrive',
            'Freshsales',
            'Insightly',
            'SugarCRM',
            'Marketing Automation',
            'Marketo',
            'Pardot',
            'Mailchimp',
            'ActiveCampaign',
            'Campaign Monitor',
            'SendGrid',
            'Constant Contact',
            'Drip',
            'Klaviyo',
            'Omnisend',
            'SMS Marketing',
            'Push Notifications',
            'Retargeting',
            'Remarketing',
            'AdWords',
            'Facebook Ads',
            'Instagram Ads',
            'LinkedIn Ads',
            'Twitter Ads',
            'Snapchat Ads',
            'TikTok Ads',
            'Pinterest Ads',
            'YouTube Ads',
            'Programmatic Advertising',
            'Native Advertising',
            'Influencer Marketing',
            'Affiliate Programs',
            'Referral Marketing',
            'Loyalty Programs',
            'Gamification',
            'Customer Retention',
            'Customer Acquisition',
            'Lead Generation',
            'Lead Nurturing',
            'Sales Enablement',
            'Pipeline Management',
            'Forecasting',
            'Quota Management',
            'Territory Management',
            'Account Management',
            'Key Account Management',
            'Channel Sales',
            'Inside Sales',
            'Outside Sales',
            'Field Sales',
            'Direct Sales',
            'Indirect Sales',
            'Reseller Programs',
            'Distribution',
            'Wholesale',
            'Retail',
            'E-commerce Platforms',
            'Marketplace',
            'Dropshipping',
            'Fulfillment',
            'Shipping',
            'Returns Management',
            'Inventory Optimization',
            'Demand Planning',
            'Order Management',
            'Procurement Automation',
            'Supplier Management',
            'Contract Management',
            'Spend Analysis',
            'Strategic Sourcing',
            'Category Management',
            'Cost Reduction',
            'Value Engineering',
            'Supplier Risk Management',
            'Supplier Diversity',
            'Sustainable Procurement',
            'Green Supply Chain',
            'Circular Supply Chain',
            'Reverse Logistics',
            'Last Mile Delivery',
            'Fleet Management',
            'Warehouse Management',
            'Cold Chain',
            'Perishable Goods',
            'Hazardous Materials',
            'Customs Compliance',
            'Trade Compliance',
            'Export Controls',
            'Import Regulations',
            'Tariffs',
            'Duties',
            'Incoterms',
            'Freight Forwarding',
            'Logistics Technology',
            'Transportation Management',
            'Route Optimization',
            'Telematics',
            'Asset Tracking',
            'RFID',
            'Barcode Scanning',
            'Inventory Tracking',
            'Stock Replenishment',
            'Cycle Counting',
            'Demand Forecasting',
            'Sales and Operations Planning',
            'Integrated Business Planning',
            'Scenario Planning',
            'Supply Chain Analytics',
            'Supply Chain Visibility',
            'Control Tower',
            'Blockchain in Supply Chain',
            'IoT in Supply Chain',
            'AI in Supply Chain',
            'Robotics in Supply Chain',
            'Drones',
            'Autonomous Vehicles',
            'Smart Warehousing',
            'Smart Factories',
            'Industry 4.0',
            'Digital Twin',
            'Additive Manufacturing',
            '3D Printing',
            'CNC Machining',
            'Injection Molding',
            'Lean Manufacturing',
            'Just-in-Time',
            'Total Productive Maintenance',
            'Overall Equipment Effectiveness',
            'Root Cause Analysis',
            'Failure Mode and Effects Analysis',
            'Statistical Process Control',
            'Quality Management Systems',
            'ISO 9001',
            'ISO 14001',
            'ISO 45001',
            'ISO 50001',
            'Environmental Management',
            'Energy Management',
            'Occupational Health and Safety',
            'Corporate Governance',
            'Board Governance',
            'Risk Governance',
            'Compliance Management',
            'Internal Audit',
            'External Audit',
            'Fraud Prevention',
            'Anti-money Laundering',
            'Sanctions Compliance',
            'Whistleblower Protection',
            'Ethics Hotline',
            'Code of Conduct',
            'Conflict of Interest',
            'Insider Trading',
            'Data Governance',
            'Master Data Management',
            'Data Quality',
            'Data Stewardship',
            'Data Lineage',
            'Metadata Management',
            'Information Security',
            'Cybersecurity Frameworks',
            'Security Architecture',
            'Zero Trust',
            'Identity and Access Management',
            'Privileged Access Management',
            'Single Sign-On',
            'Multi-factor Authentication',
            'Password Management',
            'Endpoint Security',
            'Mobile Device Management',
            'Network Security',
            'Firewall',
            'Intrusion Detection',
            'Intrusion Prevention',
            'SIEM',
            'SOAR',
            'Threat Hunting',
            'Red Team',
            'Blue Team',
            'Purple Team',
            'Bug Bounty',
            'Responsible Disclosure',
            'Security Awareness Training',
            'Phishing Simulation',
            'Vulnerability Assessment',
            'Patch Management',
            'Configuration Management',
            'Change Control',
            'Release Control',
            'Incident Response Plan',
            'Disaster Recovery Plan',
            'Business Continuity Plan',
            'Crisis Communication',
            'Tabletop Exercises',
            'After Action Review',
            'Lessons Learned',
            'Continuous Monitoring',
            'Security Metrics',
            'Key Risk Indicators',
            'Key Performance Indicators',
            'Risk Appetite',
            'Risk Tolerance',
            'Risk Register',
            'Risk Heat Map',
            'Risk Mitigation',
            'Risk Transfer',
            'Risk Acceptance',
            'Risk Avoidance',
            'Insurance',
            'Claims Management',
            'Loss Prevention',
            'Business Insurance',
            'Professional Liability',
            'General Liability',
            'Property Insurance',
            'Workers Compensation',
            'Cyber Insurance',
            'Directors and Officers Insurance',
            'Employment Practices Liability',
            'Fiduciary Liability',
            'Crime Insurance',
            'Surety Bonds',
            'Fidelity Bonds',
            'Reinsurance',
            'Captive Insurance',
            'Self-insurance',
            'Risk Financing',
            'Alternative Risk Transfer',
            'Enterprise Risk Management',
            'Strategic Risk',
            'Operational Risk',
            'Financial Risk',
            'Reputational Risk',
            'Compliance Risk',
            'Environmental Risk',
            'Social Risk',
            'Governance Risk',
            'Emerging Risk',
            'Black Swan Events',
            'Scenario Analysis',
            'Stress Testing',
            'Contingency Planning',
            'Crisis Management Team',
            'Emergency Response Team',
            'Business Impact Analysis',
            'Critical Path',
            'Recovery Time Objective',
            'Recovery Point Objective',
            'Service Level Agreement',
            'Business Service Management',
            'IT Service Management',
            'IT Asset Management',
            'Configuration Management Database',
            'Service Desk',
            'Incident Management',
            'Problem Management',
            'Change Management',
            'Release Management',
            'Service Request Management',
            'Knowledge Management',
            'Service Catalog',
            'Service Portfolio Management',
            'Capacity Management',
            'Availability Management',
            'IT Financial Management',
            'IT Vendor Management',
            'IT Strategy',
            'IT Governance',
            'IT Risk Management',
            'IT Compliance',
            'IT Audit',
            'IT Policy',
            'IT Standards',
            'IT Architecture',
            'Enterprise Architecture',
            'Solution Architecture',
            'Application Architecture',
            'Infrastructure Architecture',
            'Cloud Architecture',
            'Data Architecture',
            'Security Architecture',
            'Integration Architecture',
            'DevOps Architecture',
            'Microservices Architecture',
            'Event-driven Architecture',
            'Service-oriented Architecture',
            'Monolithic Architecture',
            'Layered Architecture',
            'Hexagonal Architecture',
            'Clean Architecture',
            'Onion Architecture',
            'Domain-driven Design',
            'Test-driven Development',
            'Behavior-driven Development',
            'Acceptance Test-driven Development',
            'Continuous Integration',
            'Continuous Delivery',
            'Continuous Deployment',
            'Infrastructure as Code',
            'Configuration as Code',
            'Policy as Code',
            'Platform Engineering',
            'Developer Experience',
            'Internal Developer Platform',
            'Self-service Infrastructure',
            'Cloud Native',
            'Cloud Agnostic',
            'Multi-cloud',
            'Hybrid Cloud',
            'Edge Computing',
            'Fog Computing',
            'Serverless Computing',
            'Function as a Service',
            'Containerization',
            'Container Orchestration',
            'Service Mesh',
            'API Management',
            'API Security',
            'API Documentation',
            'API Testing',
            'API Mocking',
            'API Monitoring',
            'API Analytics',
            'API Gateway',
            'Backend for Frontend',
            'GraphQL Federation',
            'RESTful Services',
            'gRPC Services',
            'Event Streaming',
            'Message Queues',
            'Pub/Sub',
            'Event Sourcing',
            'CQRS',
            'Saga Pattern',
            'Choreography',
            'Orchestration',
            'Distributed Tracing',
            'Observability',
            'Telemetry',
            'Metrics',
            'Logs',
            'Traces',
            'OpenTelemetry',
            'Prometheus',
            'Grafana',
            'Jaeger',
            'Zipkin',
            'Elastic Stack',
            'Splunk',
            'Datadog',
            'New Relic',
            'AppDynamics',
            'Dynatrace',
            'PagerDuty',
            'Opsgenie',
            'VictorOps',
            'StatusPage',
            'Incident.io',
            'Blameless',
            'FireHydrant',
            'Rootly',
            'Kintaba',
            'ServiceNow',
            'BMC Remedy',
            'Cherwell',
            'Freshservice',
            'Jira Service Management',
            'Zendesk',
            'SolarWinds',
            'ManageEngine',
            'Ivanti',
            'SysAid',
            'Spiceworks',
            'GLPI',
            'OTRS',
            'Request Tracker',
            'Snipe-IT',
            'Asset Panda',
            'Lansweeper',
            'Device42',
            'Qualys',
            'Tenable',
            'Rapid7',
            'Nessus',
            'OpenVAS',
            'Burp Suite',
            'OWASP ZAP',
            'Metasploit',
            'Cobalt Strike',
            'Nmap',
            'Wireshark',
            'Tcpdump',
            'Netcat',
            'Aircrack-ng',
            'John the Ripper',
            'Hashcat',
            'Hydra',
            'Nikto',
            'Dirbuster',
            'Gobuster',
            'SQLmap',
            'Wfuzz',
            'FuzzDB',
            'SecLists',
            'Amass',
            'Sublist3r',
            'TheHarvester',
            'Recon-ng',
            'Maltego',
            'Shodan',
            'Censys',
            'GreyNoise',
            'VirusTotal',
            'Hybrid Analysis',
            'Any.run',
            'Joe Sandbox',
            'Intezer Analyze',
            'Threat Intelligence Platforms',
            'MISP',
            'OpenCTI',
            'Anomali',
            'Recorded Future',
            'ThreatConnect',
            'ThreatQuotient',
            'IBM X-Force',
            'FireEye',
            'CrowdStrike',
            'Palo Alto Networks',
            'Cisco Talos',
            'Fortinet',
            'Check Point',
            'Trend Micro',
            'McAfee',
            'Symantec',
            'Sophos',
            'Kaspersky',
            'ESET',
            'Bitdefender',
            'Avast',
            'AVG',
            'Malwarebytes',
            'Webroot',
            'F-Secure',
            'G Data',
            'Comodo',
            'ZoneAlarm',
            'BullGuard',
            'Panda Security',
            'Dr.Web',
            'ClamAV',
            'Immunet',
            'Windows Defender',
            'Apple XProtect',
            'Linux Security',
            'SELinux',
            'AppArmor',
            'Firejail',
            'Lynis',
            'Chkrootkit',
            'Rootkit Hunter',
            'Tripwire',
            'AIDE',
            'OSSEC',
            'Wazuh',
            'Snort',
            'Suricata',
            'Bro/Zeek',
            'Security Onion',
            'AlienVault OSSIM',
            'SIEM Tools',
            'LogRhythm',
            'QRadar',
            'ArcSight',
            'Splunk Enterprise Security',
            'Elastic SIEM',
            'Graylog',
            'Sumo Logic',
            'Exabeam',
            'Securonix',
            'Devo',
            'Hunters',
            'Stellar Cyber',
            'LogPoint',
            'RSA NetWitness',
            'McAfee Enterprise Security Manager',
            'SolarWinds Security Event Manager',
            'ManageEngine Log360',
            'Rapid7 InsightIDR',
            'AT&T Cybersecurity',
            'FortiSIEM',
            'IBM QRadar',
            'Microsoft Sentinel',
            'Google Chronicle',
            'AWS Security Hub',
            'Azure Sentinel',
            'Cloud SIEM',
            'XDR',
            'EDR',
            'MDR',
            'SOAR Tools',
            'Cortex XSOAR',
            'Splunk Phantom',
            'IBM Resilient',
            'Swimlane',
            'DFIR',
            'Forensics',
            'Memory Analysis',
            'Disk Forensics',
            'Network Forensics',
            'Malware Analysis',
            'Reverse Engineering',
            'Static Analysis',
            'Dynamic Analysis',
            'YARA',
            'Volatility',
            'Autopsy',
            'FTK',
            'EnCase',
            'Sleuth Kit',
            'Plaso',
            'Redline',
            'Cuckoo Sandbox',
            'REMnux',
            'IDA Pro',
            'Ghidra',
            'Radare2',
            'Binary Ninja',
            'OllyDbg',
            'Immunity Debugger',
            'WinDbg',
            'x64dbg',
            'PEStudio',
            'Detect It Easy',
            'Resource Hacker',
            'Process Hacker',
            'Process Explorer',
            'Autoruns',
            'Sysinternals Suite',
            'Regshot',
            'Procmon',
            'ProcDump',
            'Strings',
            'Dependency Walker',
            'DLL Export Viewer',
            'PE Explorer',
            'UPX',
            'Packers',
            'Obfuscation',
            'Anti-debugging',
            'Anti-VM',
            'Sandbox Evasion',
            'Code Injection',
            'Process Hollowing',
            'Reflective DLL Injection',
            'DLL Hijacking',
            'COM Hijacking',
            'UAC Bypass',
            'Privilege Escalation',
            'Persistence',
            'Lateral Movement',
            'Credential Dumping',
            'Pass-the-Hash',
            'Pass-the-Ticket',
            'Kerberoasting',
            'Golden Ticket',
            'Silver Ticket',
            'DCShadow',
            'DCSync',
            'Mimikatz',
            'BloodHound',
            'SharpHound',
            'PowerView',
            'Empire',
            'Cobalt Strike',
            'Metasploit',
            'Pupy',
            'QuasarRAT',
            'NanoCore',
            'Remcos',
            'NjRAT',
            'DarkComet',
            'RATs',
            'Botnets',
            'DDoS',
            'Ransomware',
            'Phishing',
            'Spear Phishing',
            'Whaling',
            'Business Email Compromise',
            'BEC',
            'Social Engineering',
            'Pretexting',
            'Baiting',
            'Tailgating',
            'Vishing',
            'Smishing',
            'Impersonation',
            'Physical Security',
            'Access Control',
            'CCTV',
            'Alarm Systems',
            'Security Guards',
            'Perimeter Security',
            'Mantraps',
            'Biometrics',
            'Smart Cards',
            'RFID Badges',
            'Visitor Management',
            'Security Awareness',
            'Security Policy',
            'Acceptable Use Policy',
            'Data Classification',
            'Data Retention',
            'Data Destruction',
            'Media Sanitization',
            'Secure Disposal',
            'Shredding',
            'Degaussing',
            'Incineration',
            'Physical Destruction',
            'Chain of Custody',
            'Evidence Handling',
            'Legal Hold',
            'Litigation Support',
            'eDiscovery',
            'Digital Evidence',
            'Forensic Imaging',
            'Hashing',
            'MD5',
            'SHA-1',
            'SHA-256',
            'SHA-512',
            'HMAC',
            'PBKDF2',
            'bcrypt',
            'scrypt',
            'Argon2',
            'Key Derivation',
            'Key Management',
            'Public Key Infrastructure',
            'PKI',
            'Certificate Authority',
            'Digital Certificates',
            'SSL/TLS Certificates',
            'Code Signing',
            'Email Encryption',
            'PGP',
            'S/MIME',
            'Disk Encryption',
            'BitLocker',
            'FileVault',
            'VeraCrypt',
            'TrueCrypt',
            'LUKS',
            'dm-crypt',
            'eCryptfs',
            'FDE',
            'SSE',
            'TDE',
            'Database Encryption',
            'Transparent Data Encryption',
            'Column-level Encryption',
            'Field-level Encryption',
            'Tokenization',
            'Data Masking',
            'Anonymization',
            'Pseudonymization',
            'De-identification',
            'Re-identification',
            'Privacy by Design',
            'Privacy Impact Assessment',
            'Data Subject Rights',
            'Right to be Forgotten',
            'Data Portability',
            'Consent Management',
            'Cookie Consent',
            'Do Not Track',
            'Privacy Policy',
            'Terms of Service',
            'End User License Agreement',
            'EULA',
            'Service Level Agreement',
            'SLA',
            'Master Service Agreement',
            'MSA',
            'Statement of Work',
            'SOW',
            'Non-disclosure Agreement',
            'NDA',
            'Memorandum of Understanding',
            'MOU',
            'Letter of Intent',
            'LOI',
            'Partnership Agreement',
            'Joint Venture',
            'Shareholder Agreement',
            'Operating Agreement',
            'Bylaws',
            'Articles of Incorporation',
            'Business License',
            'Tax ID',
            'EIN',
            'DUNS Number',
            'SAM Registration',
            'CAGE Code',
            'NAICS Code',
            'SIC Code',
            'Business Plan',
            'Pitch Deck',
            'Executive Summary',
            'Market Analysis',
            'Competitive Analysis',
            'SWOT Analysis',
            'PESTLE Analysis',
            'Porter\'s Five Forces',
            'Value Proposition',
            'Business Model Canvas',
            'Lean Canvas',


        ];

        foreach ($tags as $tag) {
            Tag::create(['name' => $tag]);
        }

        $this->command->info('Tags seeded successfully!');
    }
}
